// flow-typed signature: 739f75374594034fc58c5f20661023ef
// flow-typed version: <<STUB>>/directory-tree_v^1.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'directory-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'directory-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'directory-tree/lib/directory-tree' {
  declare module.exports: any;
}

// Filename aliases
declare module 'directory-tree/lib/directory-tree.js' {
  declare module.exports: $Exports<'directory-tree/lib/directory-tree'>;
}
