// flow-typed signature: ea2e03b16a5f482472820b447cffabce
// flow-typed version: <<STUB>>/meteor-desktop_v^0.3.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'meteor-desktop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'meteor-desktop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'meteor-desktop/devEnvSetup' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/bin/cli' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/dependenciesManager' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/desktop' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/electron' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/electronApp' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/electronAppScaffold' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/electronBuilder' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/env' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/index' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/installerBuilder' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/log' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/meteorApp' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/packager' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/scripts/addToScripts' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/scripts/propagateVersion' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/scripts/utils/addScript' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/skeletonDependencies' {
  declare module.exports: any;
}

declare module 'meteor-desktop/dist/testSuite' {
  declare module.exports: any;
}

declare module 'meteor-desktop/scaffold/desktop' {
  declare module.exports: any;
}

declare module 'meteor-desktop/scaffold/desktop.test' {
  declare module.exports: any;
}

declare module 'meteor-desktop/scaffold/modules/example/example.test' {
  declare module.exports: any;
}

declare module 'meteor-desktop/scaffold/modules/example/index' {
  declare module.exports: any;
}

declare module 'meteor-desktop/scaffold/squirrelEvents' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/app' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/cordova' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/desktopPathResolver' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/index' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/loggerManager' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/modules/autoupdate' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/modules/autoupdate/assetBundle' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/modules/autoupdate/assetBundleDownloader' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/modules/autoupdate/assetBundleManager' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/modules/autoupdate/assetManifest' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/modules/autoupdate/isDesktopInjector' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/modules/autoupdate/utils' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/modules/dummy' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/modules/localServer' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/modules/module' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/preload' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/squirrel' {
  declare module.exports: any;
}

declare module 'meteor-desktop/skeleton/windowSettings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'meteor-desktop/devEnvSetup.js' {
  declare module.exports: $Exports<'meteor-desktop/devEnvSetup'>;
}
declare module 'meteor-desktop/dist/bin/cli.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/bin/cli'>;
}
declare module 'meteor-desktop/dist/dependenciesManager.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/dependenciesManager'>;
}
declare module 'meteor-desktop/dist/desktop.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/desktop'>;
}
declare module 'meteor-desktop/dist/electron.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/electron'>;
}
declare module 'meteor-desktop/dist/electronApp.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/electronApp'>;
}
declare module 'meteor-desktop/dist/electronAppScaffold.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/electronAppScaffold'>;
}
declare module 'meteor-desktop/dist/electronBuilder.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/electronBuilder'>;
}
declare module 'meteor-desktop/dist/env.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/env'>;
}
declare module 'meteor-desktop/dist/index.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/index'>;
}
declare module 'meteor-desktop/dist/installerBuilder.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/installerBuilder'>;
}
declare module 'meteor-desktop/dist/log.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/log'>;
}
declare module 'meteor-desktop/dist/meteorApp.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/meteorApp'>;
}
declare module 'meteor-desktop/dist/packager.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/packager'>;
}
declare module 'meteor-desktop/dist/scripts/addToScripts.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/scripts/addToScripts'>;
}
declare module 'meteor-desktop/dist/scripts/propagateVersion.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/scripts/propagateVersion'>;
}
declare module 'meteor-desktop/dist/scripts/utils/addScript.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/scripts/utils/addScript'>;
}
declare module 'meteor-desktop/dist/skeletonDependencies.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/skeletonDependencies'>;
}
declare module 'meteor-desktop/dist/testSuite.js' {
  declare module.exports: $Exports<'meteor-desktop/dist/testSuite'>;
}
declare module 'meteor-desktop/scaffold/desktop.js' {
  declare module.exports: $Exports<'meteor-desktop/scaffold/desktop'>;
}
declare module 'meteor-desktop/scaffold/desktop.test.js' {
  declare module.exports: $Exports<'meteor-desktop/scaffold/desktop.test'>;
}
declare module 'meteor-desktop/scaffold/modules/example/example.test.js' {
  declare module.exports: $Exports<'meteor-desktop/scaffold/modules/example/example.test'>;
}
declare module 'meteor-desktop/scaffold/modules/example/index.js' {
  declare module.exports: $Exports<'meteor-desktop/scaffold/modules/example/index'>;
}
declare module 'meteor-desktop/scaffold/squirrelEvents.js' {
  declare module.exports: $Exports<'meteor-desktop/scaffold/squirrelEvents'>;
}
declare module 'meteor-desktop/skeleton/app.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/app'>;
}
declare module 'meteor-desktop/skeleton/cordova.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/cordova'>;
}
declare module 'meteor-desktop/skeleton/desktopPathResolver.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/desktopPathResolver'>;
}
declare module 'meteor-desktop/skeleton/index.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/index'>;
}
declare module 'meteor-desktop/skeleton/loggerManager.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/loggerManager'>;
}
declare module 'meteor-desktop/skeleton/modules/autoupdate.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/modules/autoupdate'>;
}
declare module 'meteor-desktop/skeleton/modules/autoupdate/assetBundle.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/modules/autoupdate/assetBundle'>;
}
declare module 'meteor-desktop/skeleton/modules/autoupdate/assetBundleDownloader.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/modules/autoupdate/assetBundleDownloader'>;
}
declare module 'meteor-desktop/skeleton/modules/autoupdate/assetBundleManager.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/modules/autoupdate/assetBundleManager'>;
}
declare module 'meteor-desktop/skeleton/modules/autoupdate/assetManifest.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/modules/autoupdate/assetManifest'>;
}
declare module 'meteor-desktop/skeleton/modules/autoupdate/isDesktopInjector.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/modules/autoupdate/isDesktopInjector'>;
}
declare module 'meteor-desktop/skeleton/modules/autoupdate/utils.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/modules/autoupdate/utils'>;
}
declare module 'meteor-desktop/skeleton/modules/dummy.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/modules/dummy'>;
}
declare module 'meteor-desktop/skeleton/modules/localServer.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/modules/localServer'>;
}
declare module 'meteor-desktop/skeleton/modules/module.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/modules/module'>;
}
declare module 'meteor-desktop/skeleton/preload.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/preload'>;
}
declare module 'meteor-desktop/skeleton/squirrel.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/squirrel'>;
}
declare module 'meteor-desktop/skeleton/windowSettings.js' {
  declare module.exports: $Exports<'meteor-desktop/skeleton/windowSettings'>;
}
