// flow-typed signature: 58b3e32d5500f9c39a0dcfe0d6f35b59
// flow-typed version: <<STUB>>/react-komposer_v^2.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-komposer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-komposer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-komposer/dist/compose' {
  declare module.exports: any;
}

declare module 'react-komposer/dist/index' {
  declare module.exports: any;
}

declare module 'react-komposer/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-komposer/dist/compose.js' {
  declare module.exports: $Exports<'react-komposer/dist/compose'>;
}
declare module 'react-komposer/dist/index.js' {
  declare module.exports: $Exports<'react-komposer/dist/index'>;
}
declare module 'react-komposer/dist/utils.js' {
  declare module.exports: $Exports<'react-komposer/dist/utils'>;
}
