// flow-typed signature: 1f662919925737e5bd89a1fafc35fae5
// flow-typed version: <<STUB>>/react-router_v^4.0.0-2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/BrowserRouter' {
  declare module.exports: any;
}

declare module 'react-router/createServerRenderContext' {
  declare module.exports: any;
}

declare module 'react-router/HashRouter' {
  declare module.exports: any;
}

declare module 'react-router/Link' {
  declare module.exports: any;
}

declare module 'react-router/LocationUtils' {
  declare module.exports: any;
}

declare module 'react-router/Match' {
  declare module.exports: any;
}

declare module 'react-router/matchPattern' {
  declare module.exports: any;
}

declare module 'react-router/MatchProvider' {
  declare module.exports: any;
}

declare module 'react-router/MemoryRouter' {
  declare module.exports: any;
}

declare module 'react-router/Miss' {
  declare module.exports: any;
}

declare module 'react-router/NavigationPrompt' {
  declare module.exports: any;
}

declare module 'react-router/PropTypes' {
  declare module.exports: any;
}

declare module 'react-router/Redirect' {
  declare module.exports: any;
}

declare module 'react-router/ServerRouter' {
  declare module.exports: any;
}

declare module 'react-router/StaticRouter' {
  declare module.exports: any;
}

declare module 'react-router/umd/react-router' {
  declare module.exports: any;
}

declare module 'react-router/umd/react-router.min' {
  declare module.exports: any;
}

declare module 'react-router/website/components/App' {
  declare module.exports: any;
}

declare module 'react-router/website/components/bricks' {
  declare module.exports: any;
}

declare module 'react-router/website/components/ExampleRouter' {
  declare module.exports: any;
}

declare module 'react-router/website/components/FadeIn/index' {
  declare module.exports: any;
}

declare module 'react-router/website/components/FakeBrowser/index' {
  declare module.exports: any;
}

declare module 'react-router/website/components/LoadBundle' {
  declare module.exports: any;
}

declare module 'react-router/website/components/LoadingDots' {
  declare module.exports: any;
}

declare module 'react-router/website/components/MarkdownViewer' {
  declare module.exports: any;
}

declare module 'react-router/website/components/SourceViewer' {
  declare module.exports: any;
}

declare module 'react-router/website/examples/Ambiguous' {
  declare module.exports: any;
}

declare module 'react-router/website/examples/Animation' {
  declare module.exports: any;
}

declare module 'react-router/website/examples/Auth' {
  declare module.exports: any;
}

declare module 'react-router/website/examples/Basic' {
  declare module.exports: any;
}

declare module 'react-router/website/examples/Miss' {
  declare module.exports: any;
}

declare module 'react-router/website/examples/Params' {
  declare module.exports: any;
}

declare module 'react-router/website/examples/PreventingTransitions' {
  declare module.exports: any;
}

declare module 'react-router/website/examples/QueryParams' {
  declare module.exports: any;
}

declare module 'react-router/website/examples/Recursive' {
  declare module.exports: any;
}

declare module 'react-router/website/examples/RouteConfig' {
  declare module.exports: any;
}

declare module 'react-router/website/examples/Sidebar' {
  declare module.exports: any;
}

declare module 'react-router/website/index' {
  declare module.exports: any;
}

declare module 'react-router/website/routes' {
  declare module.exports: any;
}

declare module 'react-router/website/webpack/markdown-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/BrowserRouter.js' {
  declare module.exports: $Exports<'react-router/BrowserRouter'>;
}
declare module 'react-router/createServerRenderContext.js' {
  declare module.exports: $Exports<'react-router/createServerRenderContext'>;
}
declare module 'react-router/HashRouter.js' {
  declare module.exports: $Exports<'react-router/HashRouter'>;
}
declare module 'react-router/index' {
  declare module.exports: $Exports<'react-router'>;
}
declare module 'react-router/index.js' {
  declare module.exports: $Exports<'react-router'>;
}
declare module 'react-router/Link.js' {
  declare module.exports: $Exports<'react-router/Link'>;
}
declare module 'react-router/LocationUtils.js' {
  declare module.exports: $Exports<'react-router/LocationUtils'>;
}
declare module 'react-router/Match.js' {
  declare module.exports: $Exports<'react-router/Match'>;
}
declare module 'react-router/matchPattern.js' {
  declare module.exports: $Exports<'react-router/matchPattern'>;
}
declare module 'react-router/MatchProvider.js' {
  declare module.exports: $Exports<'react-router/MatchProvider'>;
}
declare module 'react-router/MemoryRouter.js' {
  declare module.exports: $Exports<'react-router/MemoryRouter'>;
}
declare module 'react-router/Miss.js' {
  declare module.exports: $Exports<'react-router/Miss'>;
}
declare module 'react-router/NavigationPrompt.js' {
  declare module.exports: $Exports<'react-router/NavigationPrompt'>;
}
declare module 'react-router/PropTypes.js' {
  declare module.exports: $Exports<'react-router/PropTypes'>;
}
declare module 'react-router/Redirect.js' {
  declare module.exports: $Exports<'react-router/Redirect'>;
}
declare module 'react-router/ServerRouter.js' {
  declare module.exports: $Exports<'react-router/ServerRouter'>;
}
declare module 'react-router/StaticRouter.js' {
  declare module.exports: $Exports<'react-router/StaticRouter'>;
}
declare module 'react-router/umd/react-router.js' {
  declare module.exports: $Exports<'react-router/umd/react-router'>;
}
declare module 'react-router/umd/react-router.min.js' {
  declare module.exports: $Exports<'react-router/umd/react-router.min'>;
}
declare module 'react-router/website/components/App.js' {
  declare module.exports: $Exports<'react-router/website/components/App'>;
}
declare module 'react-router/website/components/bricks.js' {
  declare module.exports: $Exports<'react-router/website/components/bricks'>;
}
declare module 'react-router/website/components/ExampleRouter.js' {
  declare module.exports: $Exports<'react-router/website/components/ExampleRouter'>;
}
declare module 'react-router/website/components/FadeIn/index.js' {
  declare module.exports: $Exports<'react-router/website/components/FadeIn/index'>;
}
declare module 'react-router/website/components/FakeBrowser/index.js' {
  declare module.exports: $Exports<'react-router/website/components/FakeBrowser/index'>;
}
declare module 'react-router/website/components/LoadBundle.js' {
  declare module.exports: $Exports<'react-router/website/components/LoadBundle'>;
}
declare module 'react-router/website/components/LoadingDots.js' {
  declare module.exports: $Exports<'react-router/website/components/LoadingDots'>;
}
declare module 'react-router/website/components/MarkdownViewer.js' {
  declare module.exports: $Exports<'react-router/website/components/MarkdownViewer'>;
}
declare module 'react-router/website/components/SourceViewer.js' {
  declare module.exports: $Exports<'react-router/website/components/SourceViewer'>;
}
declare module 'react-router/website/examples/Ambiguous.js' {
  declare module.exports: $Exports<'react-router/website/examples/Ambiguous'>;
}
declare module 'react-router/website/examples/Animation.js' {
  declare module.exports: $Exports<'react-router/website/examples/Animation'>;
}
declare module 'react-router/website/examples/Auth.js' {
  declare module.exports: $Exports<'react-router/website/examples/Auth'>;
}
declare module 'react-router/website/examples/Basic.js' {
  declare module.exports: $Exports<'react-router/website/examples/Basic'>;
}
declare module 'react-router/website/examples/Miss.js' {
  declare module.exports: $Exports<'react-router/website/examples/Miss'>;
}
declare module 'react-router/website/examples/Params.js' {
  declare module.exports: $Exports<'react-router/website/examples/Params'>;
}
declare module 'react-router/website/examples/PreventingTransitions.js' {
  declare module.exports: $Exports<'react-router/website/examples/PreventingTransitions'>;
}
declare module 'react-router/website/examples/QueryParams.js' {
  declare module.exports: $Exports<'react-router/website/examples/QueryParams'>;
}
declare module 'react-router/website/examples/Recursive.js' {
  declare module.exports: $Exports<'react-router/website/examples/Recursive'>;
}
declare module 'react-router/website/examples/RouteConfig.js' {
  declare module.exports: $Exports<'react-router/website/examples/RouteConfig'>;
}
declare module 'react-router/website/examples/Sidebar.js' {
  declare module.exports: $Exports<'react-router/website/examples/Sidebar'>;
}
declare module 'react-router/website/index.js' {
  declare module.exports: $Exports<'react-router/website/index'>;
}
declare module 'react-router/website/routes.js' {
  declare module.exports: $Exports<'react-router/website/routes'>;
}
declare module 'react-router/website/webpack/markdown-loader.js' {
  declare module.exports: $Exports<'react-router/website/webpack/markdown-loader'>;
}
